"""Детерминированное формирование и сопоставление конкурирующих гипотез v0.4.2."""
from __future__ import annotations
import json,hashlib
from itertools import combinations
from pathlib import Path
from typing import Any
from .canonical import sha256_hex,stable_id
from .temporal_validation import validate_temporal_bundle

ROOT=Path(__file__).resolve().parents[1];CATALOG=ROOT/"incident_reconstruction/rules/v0_4_2_hypothesis_rules_v1.json";BUILDER_VERSION="v0.4.2-r1"
def load_catalog():
 value=json.loads(CATALOG.read_text(encoding="utf-8"));raw=CATALOG.read_bytes().replace(b"\r\n",b"\n");return value,hashlib.sha256(raw).hexdigest()
def _id(prefix,field,value):
 x=dict(value);x[field]=stable_id(prefix,value);return x
def _hashed(prefix,field,value):
 x=_id(prefix,field,value);x["canonical_sha256"]=sha256_hex(x);return x
def build_hypothesis_analysis(bundle:dict[str,Any])->dict[str,Any]:
 validate_temporal_bundle(bundle);catalog,catalog_sha=load_catalog();tr=bundle["temporal_reconstruction"];card=bundle["source_bundle"]["incident_card"]
 model=[f for f in card["observed_facts"] if f["predicate"]=="model_classified_as"]
 qtype=str(model[0]["value"]) if model else "benign";rules=[r for r in catalog["rules"] if r["question_type"]==qtype and r["enabled"]]
 seed={"scope_type":"correlation_group","subject_ids":sorted({f["subject"] for f in card["observed_facts"]}),"event_ids":card["source_event_ids"],"episode_ids":[],"correlation_group_ids":sorted(g["group_id"] for g in tr["correlation_groups"]),"time_interval_ids":sorted(i["interval_id"] for i in tr["normalized_intervals"]),"limitations":["Область ограничена исходным temporal bundle."]};scope_id=stable_id("scope",seed)
 question=_id("question","question_id",{"schema_version":"analytical_question_v1","question_type":qtype,"question_text":f"Какие объяснения допустимы для наблюдений типа {qtype}?","scope_id":scope_id,"basis_fact_ids":sorted(f["fact_id"] for f in card["observed_facts"]),"basis_relation_ids":sorted(r["relation_id"] for r in tr["temporal_relations"]+tr["fact_relations"]),"basis_group_ids":sorted(g["group_id"] for g in tr["correlation_groups"]),"basis_gap_ids":sorted(g["gap_id"] for g in tr["gaps"]),"applicable_rule_ids":sorted(r["rule_id"] for r in rules),"limitations":["Вопрос лабораторный."]})
 scope={"schema_version":"hypothesis_scope_v1","scope_id":scope_id,"question_id":question["question_id"],**seed}
 assessments=[];hypotheses=[];profiles=[]
 facts=card["observed_facts"]
 for rule in rules:
  hseed={"rule_id":rule["rule_id"],"question_id":question["question_id"],"scope_id":scope_id,"hypothesis_type":rule["hypothesis_type"]};hid=stable_id("hyp",hseed);support=[];contra=[];neutral=[]
  seen=set()
  for fact in facts:
   source=tuple(sorted(fact["evidence_ids"]))
   if source in seen:continue
   seen.add(source);is_model=fact["fact_type"]=="model_output";is_suspicious=rule["hypothesis_type"].startswith("possible_")
   direction="context_only" if is_model else ("contradicts" if fact["predicate"]=="component_status_reported" and is_suspicious else "supports")
   abase={"schema_version":"hypothesis_evidence_assessment_v1","hypothesis_id":hid,"source_entity_type":"fact","source_entity_id":fact["fact_id"],"direction":direction,"evidence_kind":"model_output" if is_model else "observed_fact","directness":"contextual" if is_model else "directly_observed","relevance":"rule_applicable_context","duplication_group_id":stable_id("dup",source),"assessment_rule_id":"unique_canonical_source_r1","explanation_code":"model_context_only" if is_model else "observed_fact_assessment","limitations":["Оценка не является вероятностью истинности."]};a=_id("asm","assessment_id",abase);assessments.append(a);({"supports":support,"contradicts":contra}.get(direction,neutral)).append(a["assessment_id"])
  critical=sorted(g["gap_id"] for g in tr["gaps"] if g["gap_type"] in rule["critical_gap_types"]);direct=len(support);status="indeterminate" if critical else ("contradicted" if contra and not support else "partially_supported" if support else "possible")
  profile=_id("prof","profile_id",{"schema_version":"evidential_profile_v1","hypothesis_id":hid,"direct_support_count":direct,"derived_support_count":0,"contextual_support_count":len(neutral),"direct_contradiction_count":len(contra),"derived_contradiction_count":0,"critical_gap_count":len(critical),"noncritical_gap_count":len(tr["gaps"])-len(critical),"unique_support_source_count":direct,"unique_contradiction_source_count":len(contra),"duplicated_source_count":0,"profile_status":status,"derivation_rule_id":"transparent_count_profile_r1","limitations":["Профиль не является вероятностью."]});profiles.append(profile)
  h={"schema_version":"incident_hypothesis_v2","hypothesis_id":hid,"rule_id":rule["rule_id"],"question_id":question["question_id"],"scope_id":scope_id,"hypothesis_type":rule["hypothesis_type"],"title":rule["hypothesis_title_template"],"statement":rule["hypothesis_statement_template"],"status":status,"supporting_assessment_ids":sorted(support),"contradicting_assessment_ids":sorted(contra),"neutral_assessment_ids":sorted(neutral),"critical_gap_ids":critical,"noncritical_gap_ids":sorted(set(g["gap_id"] for g in tr["gaps"])-set(critical)),"alternative_hypothesis_ids":[],"comparison_ids":[],"confirmation_conditions":rule["confirmation_conditions"],"falsification_conditions":rule["falsification_conditions"],"missing_information":sorted({m for g in tr["gaps"] for m in g["missing_information"]}),"analyst_question_ids":[],"evidential_profile":profile,"limitations":rule["limitations_template"]};h["canonical_sha256"]=sha256_hex(h);hypotheses.append(h)
 for h in hypotheses:h["alternative_hypothesis_ids"]=sorted(x["hypothesis_id"] for x in hypotheses if x["hypothesis_id"]!=h["hypothesis_id"]);h["canonical_sha256"]=sha256_hex({k:v for k,v in h.items() if k!="canonical_sha256"})
 comparisons=[]
 score={p["hypothesis_id"]:(p["direct_support_count"],-p["direct_contradiction_count"],-p["critical_gap_count"]) for p in profiles}
 for left,right in combinations(hypotheses,2):
  ls,rs=score[left["hypothesis_id"]],score[right["hypothesis_id"]];result="equally_supported" if ls==rs else ("better_supported" if ls>rs else "less_supported")
  c=_hashed("cmp","comparison_id",{"schema_version":"hypothesis_comparison_v1","question_id":question["question_id"],"scope_id":scope_id,"left_hypothesis_id":left["hypothesis_id"],"right_hypothesis_id":right["hypothesis_id"],"comparison_result":result,"comparison_basis":"transparent_profile_tuple_r1","decisive_assessment_ids":[],"unresolved_difference_ids":[],"limitations":["Лучше поддержанная гипотеза не считается истинной."],"inverse_comparison_id":"pending"});comparisons.append(c)
 questions=[]
 for gap in tr["gaps"]:
  q=_id("aq","analyst_question_id",{"schema_version":"analyst_question_v1","question_id":question["question_id"],"scope_id":scope_id,"related_hypothesis_ids":sorted(h["hypothesis_id"] for h in hypotheses),"source_gap_ids":[gap["gap_id"]],"question_type":"resolve_reconstruction_gap","question_text":"Какие первичные сведения разрешают указанный разрыв реконструкции?","expected_evidence_type":"independent_primary_observation","effect_if_confirmed":"Усилить или уточнить применимые гипотезы.","effect_if_refuted":"Ослабить гипотезы, зависящие от разрыва.","requires_human_review":True,"execution_status":"not_executed","limitations":["Автоматическое выполнение запрещено."]});questions.append(q)
 for h in hypotheses:h["analyst_question_ids"]=sorted(q["analyst_question_id"] for q in questions);h["comparison_ids"]=sorted(c["comparison_id"] for c in comparisons if h["hypothesis_id"] in {c["left_hypothesis_id"],c["right_hypothesis_id"]})
 hset=_hashed("hset","hypothesis_set_id",{"schema_version":"hypothesis_set_v1","question_id":question["question_id"],"scope_id":scope_id,"hypothesis_ids":sorted(h["hypothesis_id"] for h in hypotheses),"comparison_ids":sorted(c["comparison_id"] for c in comparisons),"retained_hypothesis_ids":sorted(h["hypothesis_id"] for h in hypotheses if h["status"]!="contradicted"),"contradicted_hypothesis_ids":sorted(h["hypothesis_id"] for h in hypotheses if h["status"]=="contradicted"),"unresolved_hypothesis_ids":sorted(h["hypothesis_id"] for h in hypotheses if h["status"] in {"possible","indeterminate"}),"review_priority_hypothesis_ids":[],"forced_winner":False,"set_status":"equal_support" if len(set(score.values()))==1 else "multiple_plausible","missing_information":sorted({x for h in hypotheses for x in h["missing_information"]}),"analyst_question_ids":sorted(q["analyst_question_id"] for q in questions),"limitations":["Набор не содержит окончательного определения."]})
 explanations=[_hashed("exp","explanation_id",{"schema_version":"hypothesis_explanation_v1","hypothesis_id":h["hypothesis_id"],"rule_id":h["rule_id"],"question_id":h["question_id"],"scope_id":h["scope_id"],"supporting_items":h["supporting_assessment_ids"],"contradicting_items":h["contradicting_assessment_ids"],"missing_items":h["missing_information"],"status_derivation":"transparent_count_profile_r1","comparison_summary":h["comparison_ids"],"template_code":"hypothesis_explanation_r1","limitations":h["limitations"]}) for h in hypotheses]
 record=_hashed("rec","record_id",{"schema_version":"hypothesis_assessment_record_v1","hypothesis_set_id":hset["hypothesis_set_id"],"assessed_at_mode":"deterministic_no_wall_clock","input_bundle_sha256":sha256_hex(bundle),"rule_catalog_sha256":catalog_sha,"hypothesis_ids":hset["hypothesis_ids"],"comparison_ids":hset["comparison_ids"],"unresolved_questions":hset["analyst_question_ids"],"no_final_determination":True,"automatic_action_performed":False,"limitations":["Требуется ручное рассмотрение."]})
 base={"schema_version":"hypothesis_analysis_v1","source_temporal_bundle_id":tr["reconstruction_id"],"source_temporal_bundle_sha256":sha256_hex(bundle),"analytical_questions":[question],"hypothesis_sets":[hset],"hypotheses":sorted(hypotheses,key=lambda x:x["hypothesis_id"]),"evidence_assessments":sorted(assessments,key=lambda x:x["assessment_id"]),"evidential_profiles":sorted(profiles,key=lambda x:x["profile_id"]),"comparisons":sorted(comparisons,key=lambda x:x["comparison_id"]),"analyst_questions":sorted(questions,key=lambda x:x["analyst_question_id"]),"explanations":sorted(explanations,key=lambda x:x["explanation_id"]),"assessment_records":[record],"analysis_status":"multiple_competing_hypotheses","deterministic_build":True,"limitations":["Гипотезы не являются установленными фактами."]};analysis=_hashed("analysis","analysis_id",base);validate_analysis(analysis,catalog);return analysis
def validate_analysis(a,catalog=None):
 ids=[h["hypothesis_id"] for h in a["hypotheses"]]
 if len(ids)!=len(set(ids)):raise ValueError("duplicate_hypothesis_id")
 if any(h["status"] in {"confirmed","proven","true"} for h in a["hypotheses"]):raise ValueError("forbidden_hypothesis_status")
 if any(s["forced_winner"] for s in a["hypothesis_sets"]):raise ValueError("forced_winner_prohibited")
 if any(q["requires_human_review"] is not True or q["execution_status"]!="not_executed" for q in a["analyst_questions"]):raise ValueError("unsafe_analyst_question")
 return {"valid":True,"hypothesis_count":len(ids),"assessment_count":len(a["evidence_assessments"]),"comparison_count":len(a["comparisons"]),"analyst_question_count":len(a["analyst_questions"])}
def build_hypothesis_bundle(source):
 analysis=build_hypothesis_analysis(source);catalog,sha=load_catalog();semantic=sha256_hex(analysis);return {"schema_version":"hypothesis_analysis_bundle_v1","manifest":{"semantic_result_sha256":semantic},"source_temporal_bundle_sha256":sha256_hex(source),"source_temporal_bundle":source,"rule_catalog":catalog,"rule_catalog_sha256":sha,"hypothesis_analysis":analysis,"explanations":analysis["explanations"],"build_journal":{"steps":["inputs_validated","rules_applied","evidence_deduplicated","hypotheses_compared"]},"builder_version":BUILDER_VERSION,"standalone_verification":"passed","policy_result":{"forced_winner_count":0},"checksums":{"analysis.json":semantic},"reproducibility":{"deterministic":True,"crlf_lf_normalized":True,"network":False,"model":False,"backend":False},"limitations":["Лабораторный комплект без окончательного определения."]}
