from __future__ import annotations
import argparse,json
from pathlib import Path
SECTIONS=["Назначение","Ограничения этапа","Frozen candidate","v0.3.13 positive control","Checkpoint flag consistency","Previous-stage integrity","Protocol freeze","No-model-intervention audit","No-production-connection audit","Event contract","Event types","Event schema","Data minimization","Privacy","Canonical serialization","Event identity","Idempotency","Event hash chain","Causal event order","Source immutable prediction","Source state counts","Source-to-event reconciliation","Canonical replay","Replay equivalence","Reverse and shuffled replay","Restart and resume replay","Passive exporter","Mock sink","Delivery semantics","Queue","Priority","Backpressure","Spool","Retry","Rate limiting","Crash consistency","Fault campaign","Fail-safe behavior","Automatic action audit","Backend write audit","Production connection audit","Backend contract gap analysis","Authentication requirements","Transport requirements","Logging","Redaction","Observability","Event volume","Performance profiles","Selected profile","Latency","Throughput","CPU and RAM","GPU applicability","Load tests","Checkpoint and resume","Shadow-readiness policy","Readiness for v0.3.15","Prohibited actions","Limitations","Next stage","Conclusion"]
FILES=["protocol_freeze.json","candidate_integrity.json","v0313_positive_control.json","v0313_checkpoint_consistency_audit.json","no_model_intervention_audit.json","no_production_connection_audit.json","event_contract_freeze.json","schema_validation.json","data_minimization_audit.json","privacy_audit.json","source_reconciliation.json","causal_event_audit.json","hash_chain_audit.json","replay_equivalence.json","idempotency_audit.json","queue_audit.json","spool_recovery.json","fault_campaign_result.json","backend_contract_gap_analysis.json","performance_preflight.json","load_test_result.json","resource_summary.json","resume_audit.json","v0_3_14_policy_result.json"]
def main():
 p=argparse.ArgumentParser(); p.add_argument('--summary',required=True,type=Path); p.add_argument('--strict',action='store_true'); a=p.parse_args(); text=a.summary.read_text(encoding='utf-8'); report=a.summary.parent
 missing_sections=[s for s in SECTIONS if f"## {s}" not in text]; missing_files=[f for f in FILES if not (report/f).is_file()]; policy=json.loads((report/'v0_3_14_policy_result.json').read_text(encoding='utf-8')); resume=json.loads((report/'resume_audit.json').read_text(encoding='utf-8'))
 valid=not missing_sections and not missing_files and policy.get('v0314_shadow_readiness_completed') is True and policy.get('candidate_ready_for_shadow_mode') is False and resume.get('strict_resume_passed') is True
 print(json.dumps({'valid':valid,'missing_sections':missing_sections,'missing_files':missing_files,'strict_resume_passed':resume.get('strict_resume_passed')},ensure_ascii=False,indent=2)); return 0 if valid else 1
if __name__=='__main__': raise SystemExit(main())
