FROM --platform=linux/amd64 zeek/zeek@sha256:3d66069dc80d7bd933ead3e4aa0f001f8461448b439f06291175f6ebf27f3aa9
ARG SOURCE_DATE_EPOCH
ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
USER root
ADD --checksum=sha256:43cedfb738376d263f3f9a29b7d9b2d70c1c12e14e76a20ce7aa0a867b39dfa8 https://deb.debian.org/debian/pool/main/t/tcpdump/tcpdump_4.99.3-1_amd64.deb /tmp/tcpdump.deb
RUN dpkg-deb --extract /tmp/tcpdump.deb / && rm /tmp/tcpdump.deb
ENTRYPOINT ["tcpdump"]
